channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.6.13
- pytorch=1.9.0
- torchaudio=0.9.0
- torchvision=0.10.0
- pip
- pip:
  - pytest
  - pytest-cov
  - git+https://github.com/carefree0910/carefree-learn.git@v0.2.x